// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/common/AppIcon.vue')['default']
    BaseChart: typeof import('./components/BaseChart.vue')['default']
    GanttChart: typeof import('./components/GanttChart.vue')['default']
    LazyImg: typeof import('./components/common/LazyImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
